=== CamKem/xml-website/public/categories.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
    <xs:element name="Categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Category" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Name"/>
                            <xs:element type="xs:string" name="Image"/>
                        </xs:sequence>
                        <xs:attribute type="xs:unsignedByte" name="Id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CamKem/xml-website/public/categories.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="categories.xsl"?>
<Categories
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="categories.xsd"
>
    <Category Id="1">
        <Name>Floppy Disk Drives</Name>
        <Image>floppy.svg</Image>
    </Category>
    <Category Id="2">
        <Name>Printers</Name>
        <Image>printer.svg</Image>
    </Category>
    <Category Id="3">
        <Name>Monitors</Name>
        <Image>monitor.svg</Image>
    </Category>
    <Category Id="4">
        <Name>Keyboards</Name>
        <Image>keyboard.svg</Image>
    </Category>
    <Category Id="5">
        <Name>Peripherals</Name>
        <Image>peripherals.svg</Image>
    </Category>
</Categories>
